### ISSUE TITLE
Should it default to not setting already present environmental variables?

### ISSUE THREAD

**Issue by cymen** [azer/with-env#2]
So say PORT is already set in environment to 8080. Right now, we then ignore the value in the .env file for PORT (so process.env.PORT === 8080). It looks like foreman lets the .env override the environment. It seems like .env is more specific than the general environment so .env should override environment.

If we don't override environment, I think we should log to console saying that the key is already set to another value.

What do you think?

**Comment by MatthewMueller** [comment]
is there a way to differentiate between global env variables and ones passed in through the command line? Because this should probably override what's in `.env`:

```bash
PORT=5050 node index.js
```

**Comment by azer** [comment]
@MatthewMueller dunno
